[package]
name = "rustcombination"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="*"
blas = "0.22.0"
lapack = "0.19.0"
rayon = "1.5.2"
